---
apiVersion: apps/v1
kind: CronJob
metadata:
  name: ingestd
  labels:
    app: ingestd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestd
  template:
    metadata:
      labels:
        app: ingestd
    spec:
      containers:
      - name: efdtransform
        image: "ghcr.io/lsst-dm/consdb-efdtransform:placeholder"
        imagePullPolicy: Always
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: postgres
              key: db-uri
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3
              key: secret-access-key
        - name: EFD
          value: "usdf_efd"
        - name: LOG_FILE
          value: "/opt/lsst/software/stack/data/transform.log"
        - name: BUTLER_REPO
          value: "s3://rubin-summit-users/butler.yaml"
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "250m"
            memory: "100Mi"
