# ---

# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: transformd
#   labels:
#     app: transformd
# spec:
#   schedule: "*/5 * * * *"
#   failedJobsHistoryLimit: 3
#   jobTemplate:
#     spec:
#       template:
#         metadata:
#           labels:
#             app: transformd
#         spec:
#           restartPolicy: Never
#           containers:
#           - name: efdtransform
#             image: "ghcr.io/lsst-dm/consdb-efdtransform:placeholder"
#             imagePullPolicy: Always
#             env:
#             - name: CONFIG_FILE 
#               value: /opt/lsst/software/stack/consdb/efd_transform/config_LATISS.yaml
#             - name: INSTRUMENT
#               value: LATISS
#             - name: TIMEDELTA
#               value: "5"
#             - name: DB_URI
#               value: sqlite:////opt/lsst/software/stack/data/test.db
#             - name: EFD_USERNAME
#               value: "efdreader"
#             - name: EFD_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: usdf-efd
#                   key: usdf-efd-password
#             - name: BUTLER_REPO
#               value: "s3://rubin-summit-users/butler.yaml"
#             - name: S3_ENDPOINT_URL
#               value: https://s3dfrgw.slac.stanford.edu/
#             - name: AWS_ACCESS_KEY_ID
#               valueFrom:
#                 secretKeyRef:
#                   name: s3
#                   key: access-key-id
#             - name: AWS_SECRET_ACCESS_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: s3
#                   key: secret-access-key   
#             - name: PGUSER
#               value: rubin
#             - name: PGPASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: postgres
#                   key: butler-password              
#             - name: LOG_FILE
#               value: "/opt/lsst/software/stack/data/transform.log"              
#             resources:
#               limits:
#                 cpu: "1"
#                 memory: "500Mi"
#               requests:
#                 cpu: "250m"
#                 memory: "100Mi"
