apiVersion: v1
kind: Service
metadata:
  name: usdf-consdb-lb
  namespace: dev-latiss
spec:
  type: LoadBalancer
  selector:
    postgresql: usdf-consdb
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  loadBalancerIP: 172.24.8.136  # Replace with the desired IP
  