images:
- name: ghcr.io/lsst-dm/consdb-efdtransform
  newTag: "tickets-DM-43722"

namespace: dev-latiss

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: dev-latiss
  target:
    kind: Namespace
  options:
    allowNameChange: true

secretGenerator:
  - name: postgres
    files:
    - butler-password=etc/.secrets/butler-password
  - name: s3
    files:
    - access-key-id=etc/.secrets/access-key-id
    - secret-access-key=etc/.secrets/secret-access-key
    - s3-profile-embargo=etc/.secrets/s3-profile-embargo
  - name: usdf-efd
    files:
    - usdf-efd-password=etc/.secrets/usdf-efd-password
  - name: efd-transform-db
    files:
    - consdb-url=etc/.secrets/consdb-url
resources:
- ../../common
- consdb-transform-latiss.yaml   # uncomment to run the cronjob
# - latiss-fixed-period-job-embargo-old.yaml   # uncomment this to manually run the job using embargo old s3 bucket
