images:
- name: ghcr.io/lsst-dm/consdb-efdtransform
  newTag: "tickets-DM-43722"

namespace: dev-lsstcomcamsim

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: dev-lsstcomcamsim
  target:
    kind: Namespace
  options:
    allowNameChange: true

secretGenerator:
  - name: postgres
    files:
    - butler-password=etc/.secrets/butler-password
    - consdb-url=etc/.secrets/db-uri
  - name: s3
    files:
    - access-key-id=etc/.secrets/access-key-id
    - secret-access-key=etc/.secrets/secret-access-key
    - s3-profile-embargo=etc/.secrets/s3-profile-embargo
  - name: usdf-efd
    files:
    - usdf-efd-password=etc/.secrets/usdf-efd-password
  - name: efd-transform-db
    files:
    - consdb-url=etc/.secrets/consdb-url
resources:
- ../../common
# Periodic cronjob
- cronjob-lsstcomcamsim.yaml

# Reprocess job with embargo old (adjust the start and end dates in the manifest)
# - reprocess-lsstcomcamsim-embargo-old.yaml

# Reprocess job with embargo new (adjust the start and end dates in the manifest)
# - reprocess-lsstcomcamsim-embargo-new.yaml

# Resume failed processing job with embargo old
- resume-lsstcomcamsim-embargo-old.yaml

# Resume failed processing job with embargo new
- resume-lsstcomcamsim-embargo-new.yaml
