images:
- name: ghcr.io/lsst-dm/consdb-efdtransform
  newTag: "tickets-DM-43722"

namespace: dev-lsstcomcamsim

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: dev-lsstcomcamsim
  target:
    kind: Namespace
  options:
    allowNameChange: true

secretGenerator:
  - name: postgres
    files:
    - butler-password=etc/.secrets/butler-password
    - consdb-url=etc/.secrets/db-uri
  - name: s3
    files:
    - access-key-id=etc/.secrets/access-key-id
    - secret-access-key=etc/.secrets/secret-access-key
  - name: usdf-efd
    files:
    - usdf-efd-password=etc/.secrets/usdf-efd-password
resources:
- ../../common
- volumes.yaml
- consdb-transform-lsstcomcamsim.yaml   # uncomment to run the cronjob
# - lsstcomcamsim-fixed-period-job.yaml   # uncomment this to manually run the job
