apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/lsst-dm/consdb-transformed-efd
  newTag: "tickets-DM-43722"

resources:
- ../../../base/cronjob/

secretGenerator:
- name: efd-transform-secrets
  files:
  - butler-password=etc/.secrets/butler-password
  - aws-access-key-id=etc/.secrets/aws-access-key-id
  - aws-secret-access-key=etc/.secrets/aws-secret-access-key
  - s3-profile-embargo=etc/.secrets/s3-profile-embargo
  - usdf-efd-password=etc/.secrets/usdf-efd-password
  - consdb-url-dev=etc/.secrets/consdb-url-dev

namespace: dev-latiss

commonLabels:
  instrument: latiss

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: dev-latiss
  target:
    kind: Namespace
    name: placeholder-namespace
  options:
    allowNameChange: true

- path: patch.yaml
  target:
    kind: CronJob
    name: transformed-efd-env
  options:
    allowNameChange: true
