images:
- name: ghcr.io/lsst-dm/consdb-efdtransform
  newTag: "tickets-DM-43722"

namespace: latiss

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: latiss
  target:
    kind: Namespace
  options:
    allowNameChange: true

resources:
- ../../common
- volumes.yaml
