apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/lsst-dm/consdb-transformed-efd
  newTag: "25.5.3"

resources:
- ../../../base/job/

secretGenerator:
- name: efd-transform-secrets
  files:
  - butler-password=etc/.secrets/butler-password
  - aws-access-key-id=etc/.secrets/aws-access-key-id
  - aws-secret-access-key=etc/.secrets/aws-secret-access-key
  - s3-profile-embargo=etc/.secrets/s3-profile-embargo
  - usdf-efd-password=etc/.secrets/usdf-efd-password
  - consdb-url=etc/.secrets/consdb-url

namespace: prod-lsstcam

commonLabels:
  instrument: lsstcam

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: prod-lsstcam
  target:
    kind: Namespace
    name: placeholder-namespace
  options:
    allowNameChange: true

- path: patch.yaml
  target:
    kind: Job
    name: transformed-efd-env
  options:
    allowNameChange: true
