apiVersion: batch/v1
kind: Job
metadata:
  name: transformed-efd-prod
spec:
  template:
    spec:
      containers:
      - name: processor               
        env:                          
          - name: INSTRUMENT
            value: "LSSTCam"
          - name: CONFIG_FILE
            value: "/opt/lsst/software/stack/python/lsst/consdb/transformed_efd/config/config_lsstcam.yaml"
          - name: DATETIME_START
            value: "2025-05-01T23:00:00"      # ISOT format (UTC)
          - name: DATETIME_END
            value: "2025-05-01T23:05:00"      # ISOT format (UTC)
          - name: TIMEDELTA
            value: "5"            # Size of the processing chunks (in time, minutes)
          - name: TIMEWINDOW
            value: "1"            # Time overlap between a chunk and the next one (minutes)
          - name: CONSDB_URL
            valueFrom:
              secretKeyRef:
                name: efd-transform-secrets
                key: consdb-url
          - name: BUTLER_REPO
            value: "s3://embargo@rubin-summit-users/butler.yaml"
