---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: transformd
  labels:
    app: transformd
spec:
  schedule: "*/5 * * * *"
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: transformd
        spec:
          restartPolicy: Never
          containers:
          - name: efdtransform
            image: "ghcr.io/lsst-dm/consdb-efdtransform:placeholder"
            imagePullPolicy: Always
            command: ["/bin/bash"]
            args: ["-c", "source loadLSST.bash; setup lsst_distrib; python ./consdb/efd_transform/transform_efd.py -c \"$CONFIG_FILE\" -i \"$INSTRUMENT\" -r \"$BUTLER_REPO\" -d \"$CONSDB_URL\"  -E \"$EFD\" -t \"$TIMEDELTA\" -w \"$TIMEWINDOW\" -l \"$LOG_FILE\""]
            env:
            - name: CONFIG_FILE 
              value: /opt/lsst/software/stack/consdb/efd_transform/config_LSSTComCam.yaml
            - name: INSTRUMENT
              value: LSSTComCam
            - name: TIMEDELTA
              value: "5"
            - name : TIMEWINDOW
              value: "1"          
            - name: CONSDB_URL
              valueFrom:
                secretKeyRef:
                  name: efd-transform-db
                  key: consdb-url
            - name: EFD_USERNAME
              value: "efdreader"
            - name: EFD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: usdf-efd
                  key: usdf-efd-password
            - name: BUTLER_REPO
              value: "s3://embargo@rubin-summit-users/butler.yaml"
              # value: "/repo/embargo_old"
            - name: S3_ENDPOINT_URL
              value: https://s3dfrgw.slac.stanford.edu/
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: secret-access-key   
            - name: LSST_RESOURCES_S3_PROFILE_embargo
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: s3-profile-embargo
            - name: PGUSER
              value: rubin
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: butler-password              
            - name: LOG_FILE
              value: "/opt/lsst/software/stack/data/transform.log"              
            resources:
              limits:
                cpu: "1"
                memory: "4Gi"
              requests:
                cpu: "250m"
                memory: "2Gi"
