apiVersion: batch/v1
kind: Job
metadata:
  name: transformed-efd-dev
spec:
  template:
    spec:
      containers:
      - name: processor               
        env:                          
          - name: INSTRUMENT
            value: "LSSTCam"
          - name: CONFIG_FILE
            value: "/opt/lsst/software/stack/python/lsst/consdb/transformed_efd/config/config_lsstcam.yaml"
          - name: DATETIME_START
            value: "2025-08-15T02:00:00"      # ISOT format (UTC)
          - name: DATETIME_END
            value: "2025-08-15T02:15:00"      # ISOT format (UTC)
          - name: TIMEDELTA
            value: "5"            # Size of the processing chunks (in time, minutes)
          - name: TIMEWINDOW
            value: "1"            # Time overlap between a chunk and the next one (minutes)
          - name: CONSDB_URL
            valueFrom:
              secretKeyRef:
                name: efd-transform-secrets
                key: consdb-url-dev
          - name: BUTLER_REPO
            value: "s3://embargo@rubin-summit-users/butler.yaml"
          - name: EFD_PATH
            value: "influxdb-enterprise-standby-data"  # querying the standby node to avoid overload on the primary            

