<<<<<<< HEAD
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/lsst-dm/consdb-transformed-efd
  newTag: "tickets-DM-43722"

resources:
- ../../base/cronjob/

secretGenerator:
- name: efd-transform-secrets
  files:
  - butler-password=etc/.secrets/butler-password
  - aws-access-key-id=etc/.secrets/aws-access-key-id
  - aws-secret-access-key=etc/.secrets/aws-secret-access-key
  - s3-profile-embargo=etc/.secrets/s3-profile-embargo
  - usdf-efd-password=etc/.secrets/usdf-efd-password
  - consdb-url=etc/.secrets/consdb-url
  - consdb-url-testing=etc/.secrets/consdb-url-testing

namespace: dev-lsstcomcam

commonLabels:
  instrument: lsstcomcam

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: dev-lsstcomcam
  target:
    kind: Namespace
    name: placeholder-namespace
  options:
    allowNameChange: true

- patch: |-
    - op: replace
      path: /metadata/name
      value: transformed-efd-dev
  target:
    kind: CronJob
    name: transformed-efd-env
  options:
    allowNameChange: true

- path: patch.yaml
  target:
    kind: CronJob
    name: transformed-efd-env
  options:
    allowNameChange: true
=======
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/lsst-dm/consdb-transformed-efd
  newTag: "tickets-DM-43722"

resources:
- ../../base/cronjob/

secretGenerator:
- name: efd-transform-secrets
  files:
  - butler-password=etc/.secrets/butler-password
  - aws-access-key-id=etc/.secrets/aws-access-key-id
  - aws-secret-access-key=etc/.secrets/aws-secret-access-key
  - s3-profile-embargo=etc/.secrets/s3-profile-embargo
  - usdf-efd-password=etc/.secrets/usdf-efd-password
  - consdb-url=etc/.secrets/consdb-url
  - consdb-url-testing=etc/.secrets/consdb-url-testing

namespace: dev-lsstcomcam

commonLabels:
  instrument: lsstcomcam

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: dev-lsstcomcam
  target:
    kind: Namespace
    name: placeholder-namespace
  options:
    allowNameChange: true

- patch: |-
    - op: replace
      path: /metadata/name
      value: transformed-efd-dev
  target:
    kind: CronJob
    name: transformed-efd-env
  options:
    allowNameChange: true

- path: patch.yaml
  target:
    kind: CronJob
    name: transformed-efd-env
  options:
    allowNameChange: true
>>>>>>> 4e45772 (Fix bug in kustomization.yaml)
