images:
- name: ghcr.io/lsst-dm/consdb-efdtransform
  newTag: "tickets-DM-43722"

namespace: prod-latiss

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: prod-latiss
  target:
    kind: Namespace
  options:
    allowNameChange: true

secretGenerator:
  - name: postgres
    files:
    - butler-password=etc/.secrets/butler-password
  - name: s3
    files:
    - access-key-id=etc/.secrets/access-key-id
    - secret-access-key=etc/.secrets/secret-access-key
  - name: usdf-efd
    files:
    - usdf-efd-password=etc/.secrets/usdf-efd-password

resources:
- ../../common
- volumes.yaml
