apiVersion: batch/v1
kind: CronJob
metadata:
  name: transformed-efd-prod-failure-monitor
spec:
  schedule: "*/60 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: processor  
            env:
            - name: INSTRUMENT
              value: "LSSTCam"
            - name: CONFIG_FILE
              value: "/opt/lsst/software/stack/python/lsst/consdb/transformed_efd/config/config_lsstcam.yaml"
            - name: RESUME
              value: "--resume"     # -R or --resume Flag to resume processing from the last successful chunk
            - name: CONSDB_URL
              valueFrom:
                secretKeyRef:
                  name: efd-transform-secrets
                  key: consdb-url
            - name: BUTLER_REPO
              value: "s3://embargo@rubin-summit-users/butler.yaml"
